// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmwu3th-eyrMmSpLpJvB1hniL0G_MbdxM',
    appId: '1:646137454511:web:35abd4e98598a6561ed95a',
    messagingSenderId: '646137454511',
    projectId: 'pokedex-bloc-architecture',
    authDomain: 'pokedex-bloc-architecture.firebaseapp.com',
    storageBucket: 'pokedex-bloc-architecture.appspot.com',
    measurementId: 'G-511DPPQ6YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsjqn0VtvqnR0b-K0-o8SM9imUGBXSMLg',
    appId: '1:646137454511:android:49e6087dd772ce9e1ed95a',
    messagingSenderId: '646137454511',
    projectId: 'pokedex-bloc-architecture',
    storageBucket: 'pokedex-bloc-architecture.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaEROyz_eoGPzwZNJWVX6Q8QG0e9DULs',
    appId: '1:646137454511:ios:24f5078b2ee5cb541ed95a',
    messagingSenderId: '646137454511',
    projectId: 'pokedex-bloc-architecture',
    storageBucket: 'pokedex-bloc-architecture.appspot.com',
    iosBundleId: 'com.example.sampleBlocArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBaEROyz_eoGPzwZNJWVX6Q8QG0e9DULs',
    appId: '1:646137454511:ios:cba0aedd995de47a1ed95a',
    messagingSenderId: '646137454511',
    projectId: 'pokedex-bloc-architecture',
    storageBucket: 'pokedex-bloc-architecture.appspot.com',
    iosBundleId: 'com.example.sampleBlocArchitecture.RunnerTests',
  );
}
